### ISSUE TITLE
Examples of usage

### ISSUE THREAD

**Issue by bratao** [memeda/sequence-labeling-by-nn#5]
Hello,
Thank you for this very interesting project !

Do you plan to make it usable for as a general sequence labeling tool, or this is a code specific for a project ?

For enabling the use as a general tool, would be interesting an example of input and output, and specific how to describe the token, the tag and the features.

**Comment by fseasy** [comment]
Hi , thanks for paying attention to this ~ 
currently this repository is for building a sequence labeling model as generic as possible . For Chinese word segmentation , POSTAG , NER , SRL . Actually ,  a more self-contained project is desired to build in the end . As you know , the current repository is based on the CNN library . It is really powerful and awesome , but at last , we want to build a project to release , so we probably have to do something more. Absolutely , currently , at least recent several month , this repository is just for a general sequence labeling tool . 
currently , POSTAG is the only one had been almost implemented . 
For training , a training data is required . it is consisted of many lines , each line contains one words , like following 

我_r  喜欢_v  蓝天_n  。_wp

（Chinese is represented , so as other languages , DNN can handle it ）

what's more , developing data can also be provide , it should has the same format as training data .  pre-trained word embedding can be fed to this , or randomized initialization will be taken .  output is just on the stdout , with the acc . oh , model will be saved !  you may compile it and run to see the usage .

Tag will adapt to the specified task , and will automatic build from training data .

As it is for general model with bi-lstm , so no other features is needed . word embedding is the only input (for Chinese , may be Capital information will be used for English .)

I hope it'll be useful ~

**Comment by bratao** [comment]
Hello @memeda 
I'm revisiting this project. What an awesome progress you did in those months! 

Could you consider doing a very simple .bat or .sh with a toy data-set example to demonstrate the usage of the diverse methods you implemented ? 
This could help people evaluating your code tremendously !

And By the Way, I saw you implemented what you call ("Handcraft features"). 
Could you mind to explain what is it ? I'm my case I'm doing a sequence labeling with a lot of "special" input features such as "token Start with a comma" or "The previous token ends with a dot". 

It could use those features from the text input ? Or it need to get those features by coding it ??

Thank you for your support ! And Congratulations for been such a good developer!!

**Comment by fseasy** [comment]
Thank you for encouragement . In fact I'm down for slowly progress and uncertain future . 
It seems that many model should be built , and more experiments should be done . And I have no exact idea what to be done after testing this models .
On the other hand , I'm also very happy to do an task which seems challenging. I want to do so much , if more time will be given .  Haha , so much irrelevant :joy: .

---

**About .sh or .bat**:  I have tried to build a naive `run_flow_example` to do building and runing actions . It is not robust , and only one model is demonstrated . but you can just use `exe` to see more detailed help information  for each program . If you are on Windows , just do like project README.md , and you'll get a VS project , it'll be easier .

**About Handcraft Features** : yeah , it is just like your `special` input features .  I did it by `coding it` , because I am doing the model , instead build a general Machine Learning Algorithm Tool , like CRF++ . So I just did it in code , to _extract_ the feature from original input text . 

Hope it's useful .

**Comment by bratao** [comment]
Hahaha, keep going !

The run_flow_example is just awesome, thank you !
